account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import Login, MainProfile, UserProfile
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import *

app_name = "account"
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('account/', MainProfile.as_view(), name='home'),
    path('account/profile', UserProfile.as_view(), name='profile'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "tweet"
urlpatterns = [
    path('account/tweet', Tweety.as_view(), name='tweet'),
    path('done/', Done.as_view(), name='done'),
    path('', Index.as_view(), name='home'),
    path('account/retweet', Retweet.as_view(), name='retweet'),
    path('account/mention', Mention.as_view(), name='mention'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitterTest/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Register, activate
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('tweet.urls', 'tweet'), namespace='tweet')),
    path('', include(('account.urls', 'account'), namespace='account')),
    path('register/', Register.as_view(), name='signup'),
    path('activate/<uidb64>/<token>', activate, name='activate'),

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/models.py
import datetime
import time
from django.utils import timezone

from django.db import models


class Home(models.Model):
    photo = models.ImageField(upload_to='bg/')
    title = models.CharField(max_length=25)
    avatar = models.ImageField(upload_to='avatar/')
    name = models.CharField(max_length=20)
    date = models.DateTimeField(default=timezone.now())
    description = models.TextField(max_length=500)
    twitter = models.URLField(max_length=200)


# Create your models here.
class Tweet(models.Model):
    tweet = models.TextField(max_length=280)
    tweet_photo = models.ImageField(blank=True, upload_to='')


class Retweet(models.Model):
    query = models.CharField(max_length=400, blank=False)
    count = models.CharField(max_length=5, default=1)
    sleep = models.CharField(max_length=5, default=1)


class Mention(models.Model):
    query = models.CharField(max_length=400, blank=False)
    count = models.CharField(max_length=5, default=1)
    sleep = models.CharField(max_length=5, default=1)
    mention = models.TextField(max_length=280)

tweet/forms.py
from django import forms
from .models import Tweet, Retweet, Mention

LANGUAGE_CHOICES = [('en', 'English'),
                    ('fa', 'Persian'),
                    ('de', 'Deutsch'),
                    ('ar', 'Arabic')
                    ]


class TweetForm(forms.ModelForm):
    tweet = forms.CharField(max_length=280, required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    tweet_photo = forms.ImageField(required=False)

    class Meta:
        model = Tweet
        fields = ['tweet', 'tweet_photo']


class RetweetForm(forms.ModelForm):
    query = forms.CharField(max_length=400, min_length=3,
                            widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    count = forms.CharField(max_length=5, min_length=1,
                            widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    sleep_time = forms.CharField(max_length=5, min_length=1,
                                 widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    lang = forms.CharField(max_length=5, min_length=1,
                           widget=forms.Select(choices=LANGUAGE_CHOICES))

    class Meta:
        model = Retweet
        fields = ['query', 'count', 'sleep_time']


class MentionForm(forms.ModelForm):
    query = forms.CharField(max_length=400, min_length=3,
                            widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    mention = forms.CharField(max_length=280, min_length=2,
                              widget=forms.Textarea(attrs={'type': 'text', 'class': 'form-control'}))
    count = forms.CharField(max_length=5, min_length=1,
                            widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    sleep_time = forms.CharField(max_length=5, min_length=1,
                                 widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    lang = forms.CharField(max_length=5, min_length=1,
                           widget=forms.Select(choices=LANGUAGE_CHOICES))

    class Meta:
        model = Mention
        fields = ['query', 'mention', 'query', 'sleep_time', 'lang']

tweet/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views.generic import UpdateView, CreateView, FormView, TemplateView, DetailView
from .models import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import tweepy
from .forms import *
from .models import Home
from bs4 import BeautifulSoup
import cloudinary
from cloudinary.uploader import upload
import tempfile
from django.conf import settings
from django.core.files import File
from django.test import TestCase
import storages
from time import sleep
import requests
import os
import asyncio
from django.utils.decorators import classonlymethod


# first page will be display on site
class Index(DetailView):
    model = Home
    template_name = 'index.html'

    # get objects from model
    def get_object(self):
        home = Home.objects.first()
        return home


# successfully page
class Done(TemplateView):
    template_name = 'done.html'


def tweepy_authenticate(consumer_key, consumer_secret, access_token, access_token_secret):
    global api
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth, wait_on_rate_limit=True)


# the class which is working for sending tweet on twitter
class Tweety(FormView):
    form_class = TweetForm
    template_name = 'tweet.html'
    success_url = reverse_lazy('tweet:done')

    # get the information from form in our template
    def form_valid(self, form):
        cloudinary.config(
            cloud_name="aminsaberi",
            api_key="127435522261298",
            api_secret="VtYO5terAwp8Q_Y2LEZ1WQLqnF4"
        )
        try:
            # Authenticate The user in the twitter api
            user = self.request.user
            tweepy_authenticate(user.consumer_key, user.consumer_secret, user.access_token, user.access_token_secret)
            # getting information from form
            tweet = form.cleaned_data.get('tweet')
            photo = form.cleaned_data.get('tweet_photo')
            clean_text = BeautifulSoup(tweet, "lxml").text
            # the functions of sending tweet
            if photo:
                tweet_photo = cloudinary.uploader.upload(photo, public_id=clean_text)
                media = tweet_photo['url']
                print(media)
                filename = clean_text
                request = requests.get(media, stream=True)
                if request.status_code == 200:
                    with open(filename, 'wb') as image:
                        for chunk in request:
                            image.write(chunk)
                    api.update_with_media(filename, status=clean_text)
                    os.remove(filename)
                else:
                    print("Unable to download image")
            else:
                api.update_status(status=clean_text)
        # handle the error if we get it from tweepy
        except tweepy.TweepError as e:
            t = loader.get_template('tweepy_error.html')
            c = {'e': e}
            return HttpResponse(t.render(c, self.request))
        return super(Tweety, self).form_valid(form)


# the class which is working for retweeting on twitter
class Retweet(FormView):
    form_class = RetweetForm
    template_name = 'retweet.html'
    success_url = reverse_lazy('tweet:done')

    # get the information from form in our template
    def form_valid(self, form):
        try:
            # Authenticate The user in the twitter api
            user = self.request.user
            tweepy_authenticate(user.consumer_key, user.consumer_secret, user.access_token, user.access_token_secret)
            # getting information from form
            query = form.cleaned_data.get('query')
            count = form.cleaned_data.get('count')
            time = form.cleaned_data.get('sleep_time')
            lang = form.cleaned_data.get('lang')
            # cleaning our getting information by using bs4
            clean_text = BeautifulSoup(query, "lxml").text
            clean_count = BeautifulSoup(count, 'lxml').text
            sleep_time = BeautifulSoup(time, 'lxml').text
            clean_lang = BeautifulSoup(lang, 'lxml').text
            # the functions of auto retweet
            for tweet in tweepy.Cursor(api.search, q=(clean_text) + " -filter:mentions", count=clean_count,
                                       lang=clean_lang).items(
                int(clean_count)):
                tweet.retweet()
                id = tweet._json['id']
                api.create_favorite(id)
                sleep(int(sleep_time))
        # handle the error if we get it from tweepy
        except tweepy.TweepError as e:
            t = loader.get_template('tweepy_error.html')
            c = {'e': e}
            return HttpResponse(t.render(c, self.request))
        return super(Retweet, self).form_valid(form)


class Mention(FormView):
    template_name = 'mention.html'
    form_class = MentionForm
    success_url = reverse_lazy('tweet:done')

    def form_valid(self, form):
        try:
            # Authenticate The user in the twitter api
            user = self.request.user
            tweepy_authenticate(user.consumer_key, user.consumer_secret, user.access_token, user.access_token_secret)
            # getting information from form
            query = form.cleaned_data.get('query')
            count = form.cleaned_data.get('count')
            time = form.cleaned_data.get('sleep_time')
            text = form.cleaned_data.get('mention')
            lang = form.cleaned_data.get('lang')
            # cleaning our getting information by using bs4
            clean_count = BeautifulSoup(count, 'lxml').text
            sleep_time = BeautifulSoup(time, 'lxml').text
            mention = BeautifulSoup(text, 'lxml').text
            clean_query = BeautifulSoup(query, "lxml").text
            clean_lang = BeautifulSoup(lang, 'lxml').text
            # the functions of auto mention
            for tweet in tweepy.Cursor(api.search, q=(clean_query) + "-filter:restricted", count=int(clean_count),
                                       lang=clean_lang).items(
                int(clean_count)):
                id = tweet._json['id']
                api.update_status(mention, in_reply_to_status_id=id, auto_populate_reply_metadata=True)
                sleep(int(sleep_time))
        # handle the error if we get it from tweepy
        except tweepy.TweepError as e:
            t = loader.get_template('tweepy_error.html')
            c = {'e': e}
            return HttpResponse(t.render(c, self.request))

        return super(Mention, self).form_valid(form)

templates/ConfirmEmail.html
<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>Email Sent!</title>
    <meta name="description" content="Email Sent!">
    <style type="text/css">
        a:hover {
            text-decoration: underline !important;
        }
    </style>
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
<!--100% body table-->
<table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8"
       style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
    <tr>
        <td>
            <table style="background-color: #f2f3f8; max-width:670px;  margin:0 auto;" width="100%" border="0"
                   align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <a href="https://rakeshmandal.com" title="logo" target="_blank">
                            <img width="60" src="https://i.ibb.co/hL4XZp2/android-chrome-192x192.png" title="logo"
                                 alt="logo">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0"
                               style="max-width:670px;background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                            <tr>
                                <td style="height:40px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="padding:0 35px;">
                                    <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">
                                        Email Sent</h1>
                                    <span
                                            style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;"></span>
                                    <p style="color:#455056; font-size:15px;line-height:24px; margin:0;">
                                        Dear {{ user.username }},<br>
                                        We Just Have Sent Confirmation Link to Your Email Check Your Email:)
                                    </p>
                                    <a href="{% url 'account:login' %}"
                                       style="background:#20e277;text-decoration:none !important; font-weight:500; margin-top:35px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Login
                                        Page
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:40px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>
                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<!--/100% body table-->
</body>

</html>

templates/done.html
<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>Process Finished Successfully!</title>
    <meta name="description" content="Process Finished Successfully!">
    <style type="text/css">
        a:hover {
            text-decoration: underline !important;
        }
    </style>
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
<!--100% body table-->
<table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8"
       style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
    <tr>
        <td>
            <table style="background-color: #f2f3f8; max-width:670px;  margin:0 auto;" width="100%" border="0"
                   align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
                <tr>
                    <td style="text-align:center;">
                        <a href="https://rakeshmandal.com" title="logo" target="_blank">
                            <img width="60" src="https://i.ibb.co/hL4XZp2/android-chrome-192x192.png" title="logo"
                                 alt="logo">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0"
                               style="max-width:670px;background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                            <tr>
                                <td style="height:40px;">&nbsp;</td>
                            </tr>
                            <tr>
                                <td style="padding:0 35px;">
                                    <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">
                                        Process Finished Successfully!</h1>
                                    <span
                                            style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;"></span>
                                    <p style="color:#455056; font-size:15px;line-height:24px; margin:0;">
                                        Dear {{ user.full_name }},<br>
                                        Process Finished Successfully!
                                    </p>
                                    <a href="{% url 'account:home' %}"
                                       style="background:#20e277;text-decoration:none !important; font-weight:500; margin-top:35px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Back
                                        to Portal
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:40px;">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                <tr>
                    <td style="height:20px;">&nbsp;</td>
                </tr>
                <tr>
                    <td style="height:80px;">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<!--/100% body table-->
</body>

</html>

templates/emailConfirmation.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/index.html
<style>
    @import url('https://fonts.googleapis.com/css?family=Josefin+Sans:400,400i,600,600i');

    html, body {
        margin: 0;
        height: 120%;
        font-family: 'Josefin Sans', sans-serif;

    }

    a {
        text-decoration: none
    }

    .header {
        position: relative;
        overflow: hidden;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: flex-start;
        align-content: flex-start;
        height: 50vw;
        min-height: 400px;
        max-height: 550px;
        min-width: 300px;
        color: #eee;
    }

    .header:after {
        content: "";
        width: 100%;
        height: 100%;
        position: absolute;
        bottom: 0;
        left: 0;
        z-index: -1;
        background: linear-gradient(to bottom, rgba(0, 0, 0, 0.12) 40%, rgba(27, 32, 48, 1) 100%);
    }

    .header:before {
        content: "";
        width: 100%;
        height: 200%;
        position: absolute;
        top: 0;
        left: 0;
        -webkit-backface-visibility: hidden;
        -webkit-transform: translateZ(0);
        backface-visibility: hidden;
    scale(1.0, 1.0);
        transform: translateZ(0);
        background: #1B2030 url({{ home.photo.url }}) 50% 0 no-repeat;
        background-size: 100%;
        background-attachment: fixed;
        animation: grow 360s linear 10ms infinite;
        transition: all 0.4s ease-in-out;
        z-index: -2
    }

    .header a {
        color: #eee
    }

    .menu {
        display: block;
        width: 40px;
        height: 30px;
        border: 2px solid #fff;
        border-radius: 3px;
        position: absolute;
        right: 20px;
        top: 20px;
        text-decoration: none
    }

    .menu:after {
        content: "";
        display: block;
        width: 20px;
        height: 3px;
        background: #fff;
        position: absolute;
        margin: 0 auto;
        top: 5px;
        left: 0;
        right: 0;
        box-shadow: 0 8px, 0 16px
    }

    .logo {
        border: 2px solid #fff;
        border-radius: 3px;
        text-decoration: none;
        display: inline-flex;
        align-items: center;
        align-content: center;
        margin: 20px;
        padding: 0px 10px;
        font-weight: 900;
        font-size: 1.1em;
        line-height: 1;
        box-sizing: border-box;
        height: 40px
    }

    .sides, .info {
        flex: 0 0 auto;
        width: 50%
    }

    .info {
        width: 100%;
        padding: 15% 10% 0 10%;
        text-align: center;
        text-shadow: 0 2px 3px rgba(0, 0, 0, 0.2)
    }

    .author {
        display: inline-block;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        background: url({{ home.avatar.url }}) center no-repeat;
        background-size: cover;
        box-shadow: 0 2px 3px rgba(0, 0, 0, 0.3);
        margin-bottom: 3px
    }

    .info h4, .meta {
        font-size: 0.7em
    }

    .meta {
        font-style: italic;
    }

    @keyframes grow {
        0% {
            transform: scale(1) translateY(0px)
        }
        50% {
            transform: scale(1.2) translateY(-400px)
        }
    }

    .content {
        padding: 5% 10%;
        text-align: justify
    }

    .btn {
        color: #333;
        border: 2px solid;
        border-radius: 3px;
        text-decoration: none;
        display: inline-block;
        padding: 5px 10px;
        font-weight: 600
    }

    .twtr {
        margin-top: 100px
    }

    .btn.twtr:after {
        content: "\1F426";
        padding-left: 5px
    }
</style>

<title>Welcome to Developer Site!</title>
<div class="header">
    <div class="sides">
        {% if user.is_authenticated %}
            <a href="{% url 'account:home' %}" class="logo">Portal</a>
            <a href="{% url 'account:logout' %}" class="logo">Log Out</a>
        {% else %}
            <a href="{% url 'account:login' %}" class="logo">Login</a>
            <a href="{% url 'signup' %}" class="logo">Register</a>
        {% endif %}
    </div>
    <div class="sides"></div>
    <div class="info">
        <h4><a href="#category">Back-End Developer</a></h4>
        <h1>{{ home.title }}</h1>
        <div class="meta">
            <a href="{{ home.twitter }}" target="_b" class="author"></a><br>
            <br>
            By <a href="{{ home.twitter }}" target="_b">{{ home.name }}</a> on {{ home.date }}
        </div>
    </div>
</div>
<section class="content">
    <p>{{ home.description }}</p>
    <p align="center"><a href="{{ home.twitter }}" class="btn twtr" target="_b">Follow me on Twitter</a>
    </p>
</section>

templates/register.html
<!-- W3hubs.com - Download Free Responsive Website Layout Templates designed on HTML5
  CSS3,Bootstrap,Tailwind CSS,Shoelace Style which are 100% Mobile friendly. w3Hubs all Layouts are responsive
  cross browser supported, best quality world class designs. -->
<!DOCTYPE html>
<html>
<head>
    <title>Twitter Developer Register Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="w3hubs.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300i,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
    <style type="text/css">
        body {
            font-family: "Nunito Sans";
        }

        .login-form {
            padding: 25px;
        }

        h3 {
            padding-left: 30px;
            padding-right: 20px;
            font-weight: 700;
        }

        label {
            padding-top: 4px;
            padding-left: 4px;
        }

        .bg-color {
            background-color: rgb(245, 248, 250);
        }

        .bg-color:hover label {
            color: #31a1f2;
        }

        .btn-custom {
            background-color: #1877f2;
            border: none;
            border-radius: 6px;
            font-size: 20px;
            line-height: 28px;
            color: #fff;
            font-weight: 700;
            height: 48px;
        }

        .btn-custom {
            color: #fff !important;
            background-color: rgb(29, 161, 242);
        }

        .form-control {
            border: 0px;
            background-color: rgb(245, 248, 250);
            border-bottom: 2px solid #657786;
            padding: 0px 4px 0px 4px;
            min-height: 20px;
        }

        .form-control:focus {
            box-shadow: none;
            background-color: rgb(245, 248, 250);
            border-color: #31a1f2;
        }

        .fa {
            color: rgb(29, 161, 242);
            margin: 0 auto;
            display: block;
            text-align: center;
            font-size: 50px;
        }

        a {
            text-decoration: none;
            color: rgb(27, 149, 224);
        }

        a:hover {
            text-decoration: underline;
            color: rgb(27, 149, 224);
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 p-0 pt-3">
            <i class="fa fa-twitter"></i>
            <h3 class="text-center pt-3">Register in Developer Portal Site</h3>
            {% if form.non_field_errors %}
                <div class="errors" style="    color: red;
    background-color: #d6bcbc;
    padding: 20px 30px;">
                    {% for error in form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
            <form class="login-form" method="post">
                {% csrf_token %}
                <div class="mb-3 bg-color">
                    <label>User Name</label>
                    <br>
                    {{ form.username }}
                </div>
                {% if form.username.errors %}
                    <div class="errors" style="    color: red;
    background-color: #d6bcbc;
    padding: 20px 30px;">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="mb-3 bg-color">
                    <label>Email</label>
                    <br>
                    {{ form.email }}
                </div>
                {% if form.email.errors %}
                    <div class="errors" style="    color: red;
    background-color: #d6bcbc;
    padding: 20px 30px;">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="mb-3 bg-color">
                    <label>Password</label>
                    <br>
                    {{ form.password1 }}
                </div>
                {% if form.password1.errors %}
                    <div class="errors" style="    color: red;
    background-color: #d6bcbc;
    padding: 20px 30px;">
                        {% for error in form.password1.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="mb-3 bg-color">
                    <label>Confirm Password</label>
                    <br>
                    {{ form.password2 }}
                </div>
                {% if form.password2.errors %}
                    <div class="errors" style="    color: red;
    background-color: #d6bcbc;
    padding: 20px 30px;">
                        {% for error in form.password2.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <input type="submit" class="btn btn-custom btn-lg btn-block mt-3" value="Sign up">
            </form>
        </div>
        <center>
            <div class="col-mb-3">Already Have Account?<a href="{% url 'account:login' %}">(Login)</a></div>
        </center>
        <div class="col-md-3"></div>
    </div>
</div>
</body>
<footer>
    <style>
        #footer {
            position: fixed;
            padding: 10px 10px 0px 10px;
            bottom: 0;
            width: 100%;
            /* Height of the footer*/
            height: 40px;
            background: grey;
        }
    </style>
    <div id="footer">©2021 - All Rights Reserved To Amin Saberi.
    </div>
</footer>
</html>